### ISSUE TITLE
help i couldn't fix this following the tutorial: Unable to locate a class or view for component [app-layout].

### ISSUE THREAD

**Issue by sami-mersha** [thecodeholic/laravel11-in-1-hour#1]
![image](https://github.com/thecodeholic/laravel11-crash-course/assets/123369988/37ca1177-b4fd-4d0c-a54d-97a21c9a7acd)

**Comment by thecodeholic** [comment]
Is this file available in your project repository?
https://github.com/thecodeholic/laravel11-crash-course/blob/main/app/View/Components/AppLayout.php
